### ISSUE TITLE
Unable to deploy with AWS-CLI

### ISSUE THREAD

**Issue by pravintamil** [serverlesspub/ffmpeg-aws-lambda-layer#2]
I've tried to deploy layer from my local machine.But while deploying I'm facing some issue.

![image](https://user-images.githubusercontent.com/14850417/60720447-6c99ef00-9f48-11e9-890e-1d52a4917cc9.png)

**Comment by gojko** [comment]
what's in the output.yaml file after? can you paste the contents here? 

also, make sure you're using the latest version of aws-sdk

**Comment by pravintamil** [comment]
Hi @gojko 
Here is the content of output.yaml
```yaml
AWSTemplateFormatVersion: 2010-09-09
Description: 'Static build of FFmpeg/FFprobe for Amazon Linux 2

  Check out https://github.com/serverlesspub/ffmpeg-aws-lambda-layer for more information.

  '
Metadata:
  AWS::ServerlessRepo::Application:
    Author: Gojko Adzic
    Description: 'Static build of FFmpeg/FFprobe for Amazon Linux 2, packaged as a
      Lambda layer. Bundles FFmpeg 4.1.3

      '
    HomePageUrl: https://github.com/serverlesspub/ffmpeg-aws-lambda-layer
    Labels:
    - layer
    - lambda
    - ffmpeg
    - ffprobe
    LicenseUrl: LICENSE.txt
    Name: ffmpeg-lambda-layer
    ReadmeUrl: README-SAR.md
    SemanticVersion: 1.0.0
    SourceCodeUrl: https://github.com/serverlesspub/ffmpeg-aws-lambda-layer
    SpdxLicenseId: GPL-2.0-or-later
Outputs:
  LayerVersion:
    Description: Layer ARN Reference
    Value:
      Ref: LambdaLayer
Resources:
  LambdaLayer:
    Properties:
      CompatibleRuntimes:
      - nodejs10.x
      - python3.6
      - ruby2.5
      - java8
      - go1.x
      ContentUri: build/layer
      Description: FFMPEG for AWS Lambda
      LayerName: ffmpeg
      LicenseInfo: GPL-2.0-or-later
      RetentionPolicy: Retain
    Type: AWS::Serverless::LayerVersion
Transform: AWS::Serverless-2016-10-31

```
AWS-CLI version:
![image](https://user-images.githubusercontent.com/14850417/60721239-e337ec00-9f4a-11e9-9681-e24326dacb9d.png)
