### ISSUE TITLE
Silently failing with fluent-ffmpeg

### ISSUE THREAD

**Issue by galipmedia** [serverlesspub/ffmpeg-aws-lambda-layer#7]
I am using this layer on one lambda function absolutely fine. But no matter what I try if I setup another lambda function with the exact same layers attached  (my node_modules and this layer) it fails silently on any call. It just completely ignores the fluent-ffmpeg functions as if they are not there. I am completely baffled. I can see ffmpeg and ffprobe are there using fs readDirSync. I have tried deploying it as a second application so it gets a new arn and it still fails with 0 errors. Can anyone help me?

**Comment by MatteoGioioso** [comment]
I think I have the same problem. I have noticed a lot of timeouts.
Increasing the lambda memory helped a lot, but we are still experiencing a lot of timeout. Not sure if caused by ffmpeg or this layer itself.

**Comment by thiagocardoso1988** [comment]
I don't think I understood the problem. I'm currently using this layer alongside with fluent-ffmpeg with (almost) no problems.

I just added this in my serverless.yml, on the function that I need

```
  file_uploaded:
    handler: src/handlers/events/files.handle_upload
    timeout: 600
    memorySize: 2048
    events:
      - s3:
          bucket: "uploader-${self:provider.stage}"
          event: s3:ObjectCreated:*
    layers:
      - ${file(serverless.env.yml):${opt:stage}.env.FFMPEG_LAYER_ARN}
```

in my env file, I declared this layer:

```
local:
  region: us-east-1
  env:
    FFMPEG_LAYER_ARN: 'arn:aws:lambda:us-east-1:******:layer:ffmpeg:1'
```
